### ISSUE TITLE
Friday morning hours disappear 

### ISSUE THREAD

**Issue by WengerK** [antistatique/windmill#43]
### 💬 Describe the bug

For the account of `kevin@antistatique.net` and `iris@antistatique.net`, the hours of Friday visually disappear.

This bug is mitigated because the data are still saved in the Google Speadsheet

### 🔢 To Reproduce

Steps to reproduce the behaviour:
1. Add hours to any Friday
2. clsoe the app and re-open
3. Go to the same Friday update previouly
4. The morning hour of that Friday is disapear

### 🧞 Expected behaviour

Friday morning hour should remain visible at any time.

### 📸 Videos

https://user-images.githubusercontent.com/1841592/113684174-3feaac80-96c5-11eb-862d-bb5eb85257f5.mp4

### 📱 Smartphone:
 - Device: Pixel 4
 - OS: Android 11
 - Browser Chrome
 - Version 89

**Comment by gido** [comment]
@8uhr thanks! Can you create a "staging" Spreadsheet file for the test ?

**Comment by 8uhr** [comment]
ici : https://docs.google.com/spreadsheets/d/1fCA_Iku8AcOcKFkH2FB_O0KWjB-Ki0l8-1eb0u4VS-w/edit#gid=0

à dispo si besoin de faire des changements

**Comment by SuperQuentin** [comment]
The issue was that the friday am column time format was on automatic. The format return to windmill was invalid because it was returning on the friday morning an hour with only one digit (8:32) and not 2 digits (08:32).

![image](https://user-images.githubusercontent.com/36150436/135613616-16a5c288-d4ca-4200-989d-6fc8bd2083bf.png)

The fix was to put the same format as the others columns hh:mm on the spreadsheet.

**Comment by 8uhr** [comment]
trop bien, merci @SuperQuentin (meilleur nickname github !)
